#!/bin/bash

# Loop 20 times
for i in {1..4}
do
    # Run the curl command
    curl -XPOST 0.0.0.0:5000/files \
         -H "X-Token: 7bc4f798-be8a-4263-bbed-8231fef803ed" \
         -H "Content-Type: application/json" \
         -d '{ "name": "myText.txt", "type": "file", "data": "SGVsbG8gV2Vic3RhY2shCg==" }'

    # Print a blank line after each request
    echo ""
done

